const {
  withMainApplication,
  withMainActivity,
  withInfoPlist,
  withEntitlementsPlist,
  createRunOncePlugin,
} = require('@expo/config-plugins');

const TAG = 'twilio-voice-react-native';
const pkg = require('../package.json');

/* ------------------------------------------------------------------ utils */

function addImports(src, imports) {
  let out = src;
  for (const imp of imports) {
    if (out.includes(imp)) continue;
    // insert after the last existing import line
    const lines = out.split('\n');
    let last = -1;
    for (let i = 0; i < lines.length; i++) {
      if (/^import\s/.test(lines[i])) last = i;
    }
    if (last === -1) throw new Error(`${TAG}: no import block found`);
    lines.splice(last + 1, 0, imp);
    out = lines.join('\n');
  }
  return out;
}

/** Insert `body` as the first statement of `fun name(...) { ... }`. */
function insertAtStartOfMethod(src, signatureRegex, body, anchorAfter) {
  const m = src.match(signatureRegex);
  if (!m) return null;
  const braceIdx = src.indexOf('{', m.index + m[0].length - 1);
  if (braceIdx === -1) return null;
  let insertAt = braceIdx + 1;
  if (anchorAfter) {
    const rest = src.slice(braceIdx);
    const a = rest.match(anchorAfter);
    if (a) insertAt = braceIdx + a.index + a[0].length;
  }
  return src.slice(0, insertAt) + '\n' + body + src.slice(insertAt);
}

/**
 * Insert `body` just before the final closing brace of the file's class.
 *
 * Throws rather than returning null. Callers assign the result straight to
 * `modResults.contents`, so a null return would blank the generated file and
 * surface later as an unrelated Kotlin syntax error.
 */
function insertBeforeLastBrace(src, body) {
  const i = src.lastIndexOf('}');
  /**
   * Unreachable through any public path: every caller runs after the class
   * declaration regex matched an opening brace, so a closing brace exists. Kept
   * as an invariant guard, and excluded from coverage rather than reached by a
   * contrived test through a private door.
   */
  /* istanbul ignore next */
  if (i === -1) {
    throw new Error(`${TAG}: no closing brace found to insert before`);
  }
  return src.slice(0, i) + body + '\n' + src.slice(i);
}

/* -------------------------------------------------------- android: app */

function withVoiceMainApplication(config) {
  return withMainApplication(config, (cfg) => {
    if (cfg.modResults.language !== 'kt') {
      throw new Error(
        `${TAG}: MainApplication must be Kotlin (found ${cfg.modResults.language}).`
      );
    }
    let src = cfg.modResults.contents;

    if (src.includes('voiceApplicationProxy')) {
      cfg.modResults.contents = src;
      return cfg;
    }

    src = addImports(src, [
      'import com.twiliovoicereactnative.VoiceApplicationProxy',
    ]);

    // field on the Application class
    const withField = insertAtStartOfMethod(
      src,
      /class\s+MainApplication\s*:\s*[^{]*/,
      '  // @generated by ' +
        TAG +
        '\n  private val voiceApplicationProxy = VoiceApplicationProxy(this)\n'
    );
    if (!withField)
      throw new Error(`${TAG}: could not find class MainApplication`);
    src = withField;

    // hook onCreate, immediately after super.onCreate()
    const withOnCreate = insertAtStartOfMethod(
      src,
      /override\s+fun\s+onCreate\s*\(\s*\)\s*/,
      '    voiceApplicationProxy.onCreate() // @generated by ' + TAG,
      /super\.onCreate\(\)/
    );
    if (!withOnCreate)
      throw new Error(`${TAG}: could not find MainApplication.onCreate`);
    src = withOnCreate;

    /**
     * Same rule as the MainActivity overrides: Kotlin cannot declare
     * onTerminate twice, so a conflict must fail the prebuild rather than skip.
     * Skipping would leave voiceApplicationProxy.onTerminate() uncalled and the
     * SDK would never tear down.
     *
     * The voiceApplicationProxy early return above means any onTerminate
     * reaching here belongs to another plugin, not to a previous run of ours.
     */
    if (/override\s+fun\s+onTerminate/.test(src)) {
      throw new Error(conflictMessage('onTerminate', 'voiceApplicationProxy'));
    }
    src = insertBeforeLastBrace(
      src,
      '\n  // @generated by ' +
        TAG +
        '\n  override fun onTerminate() {' +
        '\n    voiceApplicationProxy.onTerminate()' +
        '\n    super.onTerminate()' +
        '\n  }\n'
    );

    cfg.modResults.contents = src;
    return cfg;
  });
}

/* --------------------------------------------- android: activity overrides */

/**
 * Overrides this plugin adds to MainActivity. Each must be the only declaration
 * of that method in the generated file.
 */
const ACTIVITY_OVERRIDES = [
  {
    name: 'onDestroy',
    regex: /override\s+fun\s+onDestroy/,
    body: `
  // @generated by ${TAG}
  override fun onDestroy() {
    voiceActivityProxy.onDestroy()
    super.onDestroy()
  }
`,
  },
  {
    name: 'onNewIntent',
    regex: /override\s+fun\s+onNewIntent/,
    body: `
  // @generated by ${TAG}
  override fun onNewIntent(intent: Intent) {
    super.onNewIntent(intent)
    voiceActivityProxy.onNewIntent(intent)
  }
`,
  },
];

/**
 * Build the error shown when another plugin already declares one of our
 * MainActivity overrides. States what broke, why, and the exact remedy.
 */
function conflictMessage(method, proxy = 'voiceActivityProxy') {
  const host =
    proxy === 'voiceApplicationProxy' ? 'MainApplication' : 'MainActivity';
  const arg = method === 'onNewIntent' ? 'intent' : '';
  return [
    `${TAG}: cannot add "override fun ${method}" to ${host} because another`,
    'config plugin already declares it. Kotlin does not allow two declarations',
    'of the same method, and this plugin will not edit code it does not own.',
    '',
    "To resolve, remove this plugin's Android mods and wire the SDK by hand:",
    `add the following call inside your existing ${host}.${method}, keeping`,
    'whatever else that method already does.',
    '',
    `    ${proxy}.${method}(${arg})`,
    '',
    'See docs/expo/app-config.md for the full manual wiring.',
  ].join('\n');
}

/* ---------------------------------------------------- android: activity */

function withVoiceMainActivity(config) {
  return withMainActivity(config, (cfg) => {
    if (cfg.modResults.language !== 'kt') {
      throw new Error(
        `${TAG}: MainActivity must be Kotlin (found ${cfg.modResults.language}).`
      );
    }
    let src = cfg.modResults.contents;
    if (src.includes('voiceActivityProxy')) {
      cfg.modResults.contents = src;
      return cfg;
    }

    src = addImports(src, [
      'import android.Manifest',
      'import android.content.Intent',
      'import android.os.Build',
      'import android.os.Bundle',
      'import android.widget.Toast',
      'import com.twiliovoicereactnative.VoiceActivityProxy',
    ]);

    const field = `  // @generated by ${TAG}
  private val voiceActivityProxy = VoiceActivityProxy(this) { permission ->
    when {
      Manifest.permission.RECORD_AUDIO == permission ->
        Toast.makeText(this, "Microphone permissions needed. Please allow in your application settings.", Toast.LENGTH_LONG).show()
      Build.VERSION.SDK_INT >= Build.VERSION_CODES.S &&
        Manifest.permission.BLUETOOTH_CONNECT == permission ->
        Toast.makeText(this, "Bluetooth permissions needed. Please allow in your application settings.", Toast.LENGTH_LONG).show()
      Build.VERSION.SDK_INT > Build.VERSION_CODES.S_V2 &&
        Manifest.permission.POST_NOTIFICATIONS == permission ->
        Toast.makeText(this, "Notification permissions needed. Please allow in your application settings.", Toast.LENGTH_LONG).show()
    }
  }
`;
    const withField = insertAtStartOfMethod(
      src,
      /class\s+MainActivity\s*:\s*[^{]*/,
      field
    );
    if (!withField)
      throw new Error(`${TAG}: could not find class MainActivity`);
    src = withField;

    // Expo's template already overrides onCreate(savedInstanceState: Bundle?)
    const withOnCreate = insertAtStartOfMethod(
      src,
      /override\s+fun\s+onCreate\s*\(\s*savedInstanceState\s*:\s*Bundle\?\s*\)\s*/,
      `    voiceActivityProxy.onCreate(savedInstanceState) // @generated by ${TAG}`,
      /super\.onCreate\([^)]*\)/
    );
    if (!withOnCreate) {
      throw new Error(`${TAG}: could not find MainActivity.onCreate(Bundle?)`);
    }
    src = withOnCreate;

    /**
     * Kotlin cannot declare the same override twice, so if another config
     * plugin already added one of these we cannot add ours.
     *
     * Fail the prebuild instead of skipping. Skipping silently produces an app
     * that builds, installs and then never rings, with no error anywhere. A
     * build-time failure naming the conflict is a defect the developer can see
     * and act on.
     *
     * This cannot fire on a repeated prebuild against our own output: the
     * `voiceActivityProxy` early return above catches that case first, so any
     * override reaching this point belongs to someone else.
     */
    let extras = '';
    for (const { name, regex, body } of ACTIVITY_OVERRIDES) {
      if (regex.test(src)) {
        throw new Error(conflictMessage(name));
      }
      extras += body;
    }
    src = insertBeforeLastBrace(src, extras);

    cfg.modResults.contents = src;
    return cfg;
  });
}

/* ------------------------------------------------------------------ ios */

function withVoiceInfoPlist(config, { microphoneUsageDescription }) {
  return withInfoPlist(config, (cfg) => {
    cfg.modResults.NSMicrophoneUsageDescription =
      cfg.modResults.NSMicrophoneUsageDescription || microphoneUsageDescription;
    const modes = new Set(cfg.modResults.UIBackgroundModes || []);
    modes.add('audio');
    modes.add('voip');
    cfg.modResults.UIBackgroundModes = Array.from(modes);
    return cfg;
  });
}

function withVoiceEntitlements(config, { apsEnvironment }) {
  return withEntitlementsPlist(config, (cfg) => {
    cfg.modResults['aps-environment'] =
      cfg.modResults['aps-environment'] || apsEnvironment;
    return cfg;
  });
}

/* ---------------------------------------------------------------- plugin */

const withTwilioVoice = (config, props = {}) => {
  const opts = {
    apsEnvironment: 'development',
    microphoneUsageDescription: 'This app uses the microphone for voice calls.',
    ...props,
  };

  config = withVoiceMainApplication(config);
  config = withVoiceMainActivity(config);
  config = withVoiceInfoPlist(config, opts);
  config = withVoiceEntitlements(config, opts);
  return config;
};

module.exports = createRunOncePlugin(withTwilioVoice, pkg.name, pkg.version);
