const {
  withMainApplication,
  withMainActivity,
  withProjectBuildGradle,
  withAppBuildGradle,
  withInfoPlist,
  withEntitlementsPlist,
  createRunOncePlugin,
} = require('@expo/config-plugins');

const TAG = 'twilio-voice-react-native';
const pkg = require('../package.json');

/* ------------------------------------------------------------------ utils */

function addImports(src, imports) {
  let out = src;
  for (const imp of imports) {
    if (out.includes(imp)) continue;
    // insert after the last existing import line
    const lines = out.split('\n');
    let last = -1;
    for (let i = 0; i < lines.length; i++) {
      if (/^import\s/.test(lines[i])) last = i;
    }
    if (last === -1) throw new Error(`${TAG}: no import block found`);
    lines.splice(last + 1, 0, imp);
    out = lines.join('\n');
  }
  return out;
}

/** Insert `body` as the first statement of `fun name(...) { ... }`. */
function insertAtStartOfMethod(src, signatureRegex, body, anchorAfter) {
  const m = src.match(signatureRegex);
  if (!m) return null;
  const braceIdx = src.indexOf('{', m.index + m[0].length - 1);
  if (braceIdx === -1) return null;
  let insertAt = braceIdx + 1;
  if (anchorAfter) {
    const rest = src.slice(braceIdx);
    const a = rest.match(anchorAfter);
    if (a) insertAt = braceIdx + a.index + a[0].length;
  }
  return src.slice(0, insertAt) + '\n' + body + src.slice(insertAt);
}

/** Insert `line` on the line after the first match of `anchor`. */
function insertAfterAnchor(src, anchor, line, what) {
  const m = src.match(anchor);
  if (!m) throw new Error(`${TAG}: could not find ${what}`);
  const end = m.index + m[0].length;
  return src.slice(0, end) + '\n' + line + src.slice(end);
}

/** Insert `body` just before the final closing brace of the file's class. */
function insertBeforeLastBrace(src, body) {
  const i = src.lastIndexOf('}');
  if (i === -1) return null;
  return src.slice(0, i) + body + '\n' + src.slice(i);
}

/* -------------------------------------------------------- android: app */

function withVoiceMainApplication(config) {
  return withMainApplication(config, (cfg) => {
    if (cfg.modResults.language !== 'kt') {
      throw new Error(
        `${TAG}: MainApplication must be Kotlin (found ${cfg.modResults.language}).`
      );
    }
    let src = cfg.modResults.contents;

    if (src.includes('voiceApplicationProxy')) {
      cfg.modResults.contents = src;
      return cfg;
    }

    src = addImports(src, [
      'import com.twiliovoicereactnative.VoiceApplicationProxy',
    ]);

    // field on the Application class
    const withField = insertAtStartOfMethod(
      src,
      /class\s+MainApplication\s*:\s*[^{]*/,
      '  // @generated by ' + TAG +
        '\n  private val voiceApplicationProxy = VoiceApplicationProxy(this)\n'
    );
    if (!withField) throw new Error(`${TAG}: could not find class MainApplication`);
    src = withField;

    // hook onCreate, immediately after super.onCreate()
    const withOnCreate = insertAtStartOfMethod(
      src,
      /override\s+fun\s+onCreate\s*\(\s*\)\s*/,
      '    voiceApplicationProxy.onCreate() // @generated by ' + TAG,
      /super\.onCreate\(\)/
    );
    if (!withOnCreate) throw new Error(`${TAG}: could not find MainApplication.onCreate`);
    src = withOnCreate;

    // add onTerminate
    if (!/override\s+fun\s+onTerminate/.test(src)) {
      src = insertBeforeLastBrace(
        src,
        '\n  // @generated by ' + TAG +
          '\n  override fun onTerminate() {' +
          '\n    voiceApplicationProxy.onTerminate()' +
          '\n    super.onTerminate()' +
          '\n  }\n'
      );
    }

    cfg.modResults.contents = src;
    return cfg;
  });
}

/* ---------------------------------------------------- android: activity */

function withVoiceMainActivity(config) {
  return withMainActivity(config, (cfg) => {
    if (cfg.modResults.language !== 'kt') {
      throw new Error(
        `${TAG}: MainActivity must be Kotlin (found ${cfg.modResults.language}).`
      );
    }
    let src = cfg.modResults.contents;
    if (src.includes('voiceActivityProxy')) {
      cfg.modResults.contents = src;
      return cfg;
    }

    src = addImports(src, [
      'import android.Manifest',
      'import android.content.Intent',
      'import android.os.Build',
      'import android.os.Bundle',
      'import android.widget.Toast',
      'import com.twiliovoicereactnative.VoiceActivityProxy',
    ]);

    const field = `  // @generated by ${TAG}
  private val voiceActivityProxy = VoiceActivityProxy(this) { permission ->
    when {
      Manifest.permission.RECORD_AUDIO == permission ->
        Toast.makeText(this, "Microphone permissions needed. Please allow in your application settings.", Toast.LENGTH_LONG).show()
      Build.VERSION.SDK_INT >= Build.VERSION_CODES.S &&
        Manifest.permission.BLUETOOTH_CONNECT == permission ->
        Toast.makeText(this, "Bluetooth permissions needed. Please allow in your application settings.", Toast.LENGTH_LONG).show()
      Build.VERSION.SDK_INT > Build.VERSION_CODES.S_V2 &&
        Manifest.permission.POST_NOTIFICATIONS == permission ->
        Toast.makeText(this, "Notification permissions needed. Please allow in your application settings.", Toast.LENGTH_LONG).show()
    }
  }
`;
    const withField = insertAtStartOfMethod(
      src,
      /class\s+MainActivity\s*:\s*[^{]*/,
      field
    );
    if (!withField) throw new Error(`${TAG}: could not find class MainActivity`);
    src = withField;

    // Expo's template already overrides onCreate(savedInstanceState: Bundle?)
    const withOnCreate = insertAtStartOfMethod(
      src,
      /override\s+fun\s+onCreate\s*\(\s*savedInstanceState\s*:\s*Bundle\?\s*\)\s*/,
      `    voiceActivityProxy.onCreate(savedInstanceState) // @generated by ${TAG}`,
      /super\.onCreate\([^)]*\)/
    );
    if (!withOnCreate) {
      throw new Error(`${TAG}: could not find MainActivity.onCreate(Bundle?)`);
    }
    src = withOnCreate;

    let extras = '';
    if (!/override\s+fun\s+onDestroy/.test(src)) {
      extras += `
  // @generated by ${TAG}
  override fun onDestroy() {
    voiceActivityProxy.onDestroy()
    super.onDestroy()
  }
`;
    }
    if (!/override\s+fun\s+onNewIntent/.test(src)) {
      extras += `
  // @generated by ${TAG}
  override fun onNewIntent(intent: Intent) {
    super.onNewIntent(intent)
    voiceActivityProxy.onNewIntent(intent)
  }
`;
    }
    if (extras) src = insertBeforeLastBrace(src, extras);

    cfg.modResults.contents = src;
    return cfg;
  });
}

/* ------------------------------------------------------ android: gradle */

function withVoiceProjectGradle(config, { googleServicesVersion }) {
  return withProjectBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') {
      throw new Error(`${TAG}: project build.gradle must be groovy`);
    }
    if (cfg.modResults.contents.includes('com.google.gms:google-services')) {
      return cfg;
    }
    cfg.modResults.contents = insertAfterAnchor(
      cfg.modResults.contents,
      /dependencies\s*\{/,
      `        classpath('com.google.gms:google-services:${googleServicesVersion}') // @generated by ${TAG}`,
      'a dependencies block in the project build.gradle'
    );
    return cfg;
  });
}

function withVoiceAppGradle(config) {
  return withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.contents.includes('com.google.gms.google-services')) {
      return cfg;
    }
    cfg.modResults.contents = insertAfterAnchor(
      cfg.modResults.contents,
      /apply plugin: ["']com\.android\.application["']/,
      `apply plugin: "com.google.gms.google-services" // @generated by ${TAG}`,
      'the com.android.application plugin line in the app build.gradle'
    );
    return cfg;
  });
}

/* ------------------------------------------------------------------ ios */

function withVoiceInfoPlist(config, { microphoneUsageDescription }) {
  return withInfoPlist(config, (cfg) => {
    cfg.modResults.NSMicrophoneUsageDescription =
      cfg.modResults.NSMicrophoneUsageDescription || microphoneUsageDescription;
    const modes = new Set(cfg.modResults.UIBackgroundModes || []);
    modes.add('audio');
    modes.add('voip');
    cfg.modResults.UIBackgroundModes = Array.from(modes);
    return cfg;
  });
}

function withVoiceEntitlements(config, { apsEnvironment }) {
  return withEntitlementsPlist(config, (cfg) => {
    cfg.modResults['aps-environment'] =
      cfg.modResults['aps-environment'] || apsEnvironment;
    return cfg;
  });
}

/* ---------------------------------------------------------------- plugin */

const withTwilioVoice = (config, props = {}) => {
  const opts = {
    apsEnvironment: 'development',
    microphoneUsageDescription: 'This app uses the microphone for voice calls.',
    googleServicesVersion: '4.4.1',
    ...props,
  };

  config = withVoiceMainApplication(config);
  config = withVoiceMainActivity(config);
  config = withVoiceProjectGradle(config, opts);
  config = withVoiceAppGradle(config);
  config = withVoiceInfoPlist(config, opts);
  config = withVoiceEntitlements(config, opts);
  return config;
};

module.exports = createRunOncePlugin(withTwilioVoice, pkg.name, pkg.version);
