/**
 * Copyright © 2022 Twilio, Inc. All rights reserved. Licensed under the Twilio
 * license.
 *
 * See LICENSE in the project root for license information.
 */

import { NativeModule } from './common';
import type { NativeAudioDeviceInfo } from './type/AudioDevice';
import type { Uuid } from './type/common';

/**
 * Describes audio devices as reported by the native layer and allows the
 * native selection of the described audio device.
 *
 * @remarks
 * To fetch a list of available audio devices and the currently selected audio
 * device, see {@link (Voice:class).getAudioDevices}.
 *
 *  - See also the {@link (AudioDevice:namespace) | AudioDevice namespace} for
 *    types used by this class.
 *
 * @public
 */
export class AudioDevice {
  /**
   * The native-UUID of this object. This is generated by the native layer and
   * is used to associate functionality between the JS and native layers.
   *
   * @internal
   */
  uuid: Uuid;

  /**
   * The type of the audio device.
   *
   * @remarks
   * This is a best-effort categorization of {@link (AudioDevice:class).nativeType}
   * into one of the well-known {@link (AudioDevice:namespace).Type} values. If the
   * native layer reports a device type that this SDK does not recognize, this will be
   * {@link (AudioDevice:namespace).Type.Unknown}; see
   * {@link (AudioDevice:class).nativeType} for the raw, unprocessed value in that
   * case.
   */
  type: AudioDevice.Type;

  /**
   * The type of the audio device as reported verbatim by the native layer, without
   * being mapped to a {@link (AudioDevice:namespace).Type}.
   *
   * @remarks
   * Native platform APIs can report audio device types that are not represented by
   * {@link (AudioDevice:namespace).Type}, for example due to OS updates introducing
   * new device categories. This field is provided as an escape hatch for those cases
   * and its value is not guaranteed to be stable across native SDK or OS versions.
   *
   * On iOS platforms, these values correlate to the Apple-defined
   * `AVAudioSessionPort` constant.
   *
   * On Android platforms, these values correlate to the class names found in the
   * Twilio AudioSwitch library.
   */
  nativeType: string;

  /**
   * The name of the audio device.
   */
  name: string;

  /**
   * Audio device class constructor.
   * @param audioDeviceInformation - A record describing an audio device.
   *
   * @internal
   */
  constructor({ uuid, type, nativeType, name }: NativeAudioDeviceInfo) {
    this.uuid = uuid;
    this.type = type;
    this.nativeType = nativeType;
    this.name = name;
  }

  /**
   * Calling this method will select this audio device as the active audio
   * device.
   * @returns
   *  A `Promise` that
   *    - Resolves with `void` when the audio device has been successfully
   *      selected as the active audio device.
   *    - Rejects if the audio device cannot be selected.
   */
  async select(): Promise<void> {
    await NativeModule.voice_selectAudioDevice(this.uuid);
  }
}

/**
 * Contains interfaces and enumerations associated with audio devices.
 *
 * @remarks
 *  - See also the {@link (AudioDevice:class) | AudioDevice class}.
 *
 * @public
 */
export namespace AudioDevice {
  /**
   * Audio device type enumeration. Describes the well-known audio device types
   * recognized by this SDK.
   *
   * @remarks
   * The native layer can report device types outside of this enumeration, for
   * example due to OS updates introducing new device categories. In those cases,
   * the {@link (AudioDevice:class) | AudioDevice} `type` property is
   * {@link (AudioDevice:namespace).Type.Unknown} and
   * {@link (AudioDevice:class).nativeType} carries the raw, unprocessed value.
   */
  export enum Type {
    /**
     * Audio device type representing an earpiece.
     */
    Earpiece = 'earpiece',

    /**
     * Audio device type representing a speaker.
     */
    Speaker = 'speaker',

    /**
     * Audio device type representing a Bluetooth device.
     */
    Bluetooth = 'bluetooth',

    /**
     * Audio device type representing a device that is not recognized as one
     * of the other well-known {@link (AudioDevice:namespace).Type} values.
     *
     * @remarks
     * See {@link (AudioDevice:class).nativeType} for the raw, unprocessed
     * device type reported by the native layer in this case.
     */
    Unknown = 'unknown',
  }
}
